name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DOCKER_IMAGE: us-central1-docker.pkg.dev/decent-tape-469610-j5/notely-ar-repo/notely:latest


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build PRoduction file
        run: ./scripts/buildprod.sh

      - name: Run DB migration
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'push to Google Artifact Registry'
        run: gcloud builds submit --tag DOCKER_IMAGE

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image DOCKER_IMAGE --region us-central1 --allow-unauthenticated --project decent-tape-469610-j5 --max-instances=4
